export default {
    FPS: 50,

    BRICK_WIDTH: 32,
    BRICK_HEIGHT: 16,
	PLAYER_WIDTH: 20,
	
    PLAYER_MAX_VELOCITY_X: 3,
	
	
	// DDEMO
	DDEMO_VERSION: 0,     // here is a version of the demo engine... reading from demofile
	DDEMO_FIREROCKET: 1,
	DDEMO_PLAYERPOS: 2, // unused (old version)
	DDEMO_TIMESET: 3,
	DDEMO_CREATEPLAYER: 4,
	DDEMO_KILLOBJECT: 5,
	DDEMO_FIREBFG: 6,
	DDEMO_FIREPLASMA: 7,
	DDEMO_FIREGREN: 8,
	DDEMO_FIRERAIL: 9,
	DDEMO_FIRESHAFT: 10,
	DDEMO_FIRESHOTGUN: 11,
	DDEMO_FIREMACH: 12,
	DDEMO_ITEMDISSAPEAR: 13,
	DDEMO_ITEMAPEAR: 14,
	DDEMO_DAMAGEPLAYER: 15,
	DDEMO_HAUPDATE: 16,
	DDEMO_FLASH: 17,
	DDEMO_JUMPSOUND: 18,
	DDEMO_GAMEEND: 19,
	DDEMO_RESPAWNSOUND: 20,
	DDEMO_JUMPPADSOUND: 21,
	DDEMO_LAVASOUND: 22,
	DDEMO_POWERUPSOUND: 23,
	DDEMO_EARNPOWERUP: 24,
	DDEMO_READYPRESS: 25,
	DDEMO_FLIGHTSOUND: 26,
	DDEMO_EARNREWARD: 27,
	DDEMO_STATS: 28, // unused (old version)
	DDEMO_GAMESTATE: 29,
	DDEMO_TRIXARENAEND: 30,
	DDEMO_OBJCHANGESTATE: 31,
	DDEMO_CORPSESPAWN: 32,
	DDEMO_GRENADESYNC: 33,
	DDEMO_STATS2: 34, // unused (old version)
	DDEMO_PLAYERPOSV2: 35, // unused (old version)
	DDEMO_FIREGRENV2: 36,
	DDEMO_NOAMMOSOUND: 37,
	DDEMO_GAUNTLETSTATE: 38,
	DDEMO_STATS3: 39,
	DDEMO_FIREPLASMAV2: 40,
	DDEMO_PLAYERPOSV3: 41,
	DDEMO_BUBBLE: 42,
	//multiplayer
	DDEMO_MPSTATE: 43,
	DDEMO_NETRAIL: 44, //clients.
	DDEMO_NETPARTICLE: 45, //clients
	DDEMO_NETTIMEUPDATE: 46, //only clients.
	DDEMO_NETSVMATCHSTART: 47, //only clients.
	DDEMO_DROPPLAYER: 48,
	DDEMO_CREATEPLAYERV2: 49,
	DDEMO_SPECTATORCONNECT: 50,
	DDEMO_SPECTATORDISCONNECT: 51,
	DDEMO_CHATMESSAGE: 52,
	DDEMO_PLAYERRENAME: 53,
	DDEMO_PLAYERMODELCHANGE: 54,
	DDEMO_GENERICSOUNDDATA: 55,
	DDEMO_GENERICSOUNDSTATDATA: 56,
	DDEMO_TEAMSELECT: 57,
	DDEMO_CTF_EVENT_FLAGTAKEN: 58,
	DDEMO_CTF_EVENT_FLAGCAPTURE: 59,
	DDEMO_CTF_EVENT_FLAGDROP: 60,
	DDEMO_CTF_EVENT_FLAGPICKUP: 61,
	DDEMO_CTF_EVENT_FLAGDROP_APPLY: 62,
	DDEMO_CTF_EVENT_FLAGRETURN: 63,
	DDEMO_CTF_GAMESTATE: 64,
	DDEMO_CTF_EVENT_FLAGDROPGAMESTATE: 65,
	DDEMO_CTF_GAMESTATESCORE: 66,
	DDEMO_CTF_FLAGCARRIER: 67,
	DDEMO_DOM_CAPTURE: 68,
	DDEMO_DOM_SCORECHANGED: 69,
	DDEMO_WPN_EVENT_WEAPONDROP: 70,
	DDEMO_WPN_EVENT_PICKUP: 71,
	DDEMO_WPN_EVENT_WEAPONDROP_APPLY: 72,
	DDEMO_WPN_EVENT_WEAPONDROPGAMESTATE: 73,
	DDEMO_DOM_CAPTUREGAMESTATE: 74,
	DDEMO_NEW_SHAFTBEGIN: 75,
	DDEMO_NEW_SHAFTEND: 76,
	DDEMO_POWERUP_EVENT_POWERUPDROP: 77,
	DDEMO_POWERUP_EVENT_PICKUP: 78,
	DDEMO_POWERUP_EVENT_POWERUPDROPGAMESTATE: 79,

	// conn: additional demo ctf events
	DDEMO_CTF_EVENT_FLAGTAKEN_RED     : 80,
	DDEMO_CTF_EVENT_FLAGCAPTURE_RED   : 81,
	DDEMO_CTF_EVENT_FLAGDROP_RED      : 82
	
};

