
export default {
    FPS: 50, // used in demo and timers (do not change, this is initial NFK fps)

    BRICK_WIDTH: 32,
    BRICK_HEIGHT: 16,
	
	PLAYER_WIDTH: 20,
	PLAYER_HEIGHT: 16 * 3,
	PLAYER_HEIGHT_CROUCH: 16 * 2,
	
    PLAYER_MAX_VELOCITY_X: 3,
	

	// team
	C_TEAMBLUE : 0,  
	C_TEAMRED : 1,
	C_TEAMNON : 2,

	 // weapon ID
	C_WPN_GAUNTLET:0,
	C_WPN_MACHINE:1,
	C_WPN_SHOTGUN:2,
	C_WPN_GRENADE:3,
	C_WPN_ROCKET:4,
	C_WPN_SHAFT:5,
	C_WPN_RAIL:6,
	C_WPN_PLASMA:7,
	C_WPN_BFG:8,


	// model direction & current animation status.
	DIR_LW: 0, // walkin left
	DIR_RW: 1, // walkin right
	DIR_LS: 2, // standin left
	DIR_RS: 3, // standin right


	GAMETYPE_FFA : 0,
	GAMETYPE_1V1 : 1,
	GAMETYPE_TEAM : 2,
	GAMETYPE_CTF : 3,
	GAMETYPE_RAILARENA : 4,
	GAMETYPE_TRIXARENA : 5,
	GAMETYPE_PRACTICE : 6,
	GAMETYPE_DOMINATION : 7,
	COLORARRAY : [0xFFFFFFF, 0xFF000080, 0xFF008000,0xFF800000, 0xFF800080, 0xFF808000, 0xFF808080, 0xFFC0C0C0, 0xFF0000FF, 0xFF00FF00,
			0xFF00FFFF, 0xFFFF0000, 0xFFFF00FF, 0xFFFFFF00, 0xFFC0C0C0, 0xFF808080, 0xFF000000],

	// values returned by GetBrickStruct() ... (TBrick.image)
	IT_NONE    : 0,
	IT_SHOTGUN : 1,
	IT_GRENADE : 2,
	IT_ROCKET  : 3,
	IT_SHAFT   : 4,
	IT_RAIL    : 5,
	IT_PLASMA  : 6,
	IT_BFG     : 7,
	IT_AMMO_MACHINEGUN : 8,
	IT_AMMO_SHOTGUN    : 9,
	IT_AMMO_GRENADE    : 10,
	IT_AMMO_ROCKET     : 11,
	IT_AMMO_SHAFT      : 12,
	IT_AMMO_RAIL       : 13,
	IT_AMMO_PLASMA     : 14,
	IT_AMMO_BFG        : 15,
	IT_SHARD           : 16,
	IT_YELLOW_ARMOR    : 17,
	IT_RED_ARMOR       : 18,
	IT_HEALTH_5        : 19,
	IT_HEALTH_25       : 20,
	IT_HEALTH_50       : 21,
	IT_HEALTH_100      : 22, // megahealth
	IT_POWERUP_REGENERATION : 23,
	IT_POWERUP_BATTLESUIT   : 24,
	IT_POWERUP_HASTE        : 25,
	IT_POWERUP_QUAD         : 26,
	IT_POWERUP_FLIGHT       : 27,
	IT_POWERUP_INVISIBILITY : 28,
	IT_TRIX_GRENADE : 29, // will never used by bot.dll
	IT_TRIX_ROCKET  : 30, // will never used by bot.dll
	IT_LAVA         : 31,
	IT_WATER        : 32,
	IT_DEATH        : 33,
	IT_RESPAWN      : 34, // not used. use GetBrickStruct() to handle this
	IT_RED_RESPAWN  : 35, // not used. use GetBrickStruct() to handle this
	IT_BLUE_RESPAWN : 36, // not used. use GetBrickStruct() to handle this
	IT_EMPTY        : 37,
	IT_JUMPPAD      : 38,
	IT_JUMPPAD2     : 39, // strong
	IT_BLUE_FLAG    : 40,
	IT_RED_FLAG     : 41,
	IT_DOMINATION_FLAG : 42, // use GetBrickStruct() to get color.


	// DDEMO
	DDEMO_VERSION: 0,     // here is a version of the demo engine... reading from demofile
	DDEMO_FIREROCKET: 1,
	DDEMO_PLAYERPOS: 2, // unused (old version)
	DDEMO_TIMESET: 3,
	DDEMO_CREATEPLAYER: 4,
	DDEMO_KILLOBJECT: 5,
	DDEMO_FIREBFG: 6,
	DDEMO_FIREPLASMA: 7,
	DDEMO_FIREGREN: 8,
	DDEMO_FIRERAIL: 9,
	DDEMO_FIRESHAFT: 10,
	DDEMO_FIRESHOTGUN: 11,
	DDEMO_FIREMACH: 12,
	DDEMO_ITEMDISSAPEAR: 13,
	DDEMO_ITEMAPEAR: 14,
	DDEMO_DAMAGEPLAYER: 15,
	DDEMO_HAUPDATE: 16,
	DDEMO_FLASH: 17,
	DDEMO_JUMPSOUND: 18,
	DDEMO_GAMEEND: 19,
	DDEMO_RESPAWNSOUND: 20,
	DDEMO_JUMPPADSOUND: 21,
	DDEMO_LAVASOUND: 22,
	DDEMO_POWERUPSOUND: 23,
	DDEMO_EARNPOWERUP: 24,
	DDEMO_READYPRESS: 25,
	DDEMO_FLIGHTSOUND: 26,
	DDEMO_EARNREWARD: 27,
	DDEMO_STATS: 28, // unused (old version)
	DDEMO_GAMESTATE: 29,
	DDEMO_TRIXARENAEND: 30,
	DDEMO_OBJCHANGESTATE: 31,
	DDEMO_CORPSESPAWN: 32,
	DDEMO_GRENADESYNC: 33,
	DDEMO_STATS2: 34, // unused (old version)
	DDEMO_PLAYERPOSV2: 35, // unused (old version)
	DDEMO_FIREGRENV2: 36,
	DDEMO_NOAMMOSOUND: 37,
	DDEMO_GAUNTLETSTATE: 38,
	DDEMO_STATS3: 39,
	DDEMO_FIREPLASMAV2: 40,
	DDEMO_PLAYERPOSV3: 41,
	DDEMO_BUBBLE: 42,
	//multiplayer
	DDEMO_MPSTATE: 43,
	DDEMO_NETRAIL: 44, //clients.
	DDEMO_NETPARTICLE: 45, //clients
	DDEMO_NETTIMEUPDATE: 46, //only clients.
	DDEMO_NETSVMATCHSTART: 47, //only clients.
	DDEMO_DROPPLAYER: 48,
	DDEMO_CREATEPLAYERV2: 49,
	DDEMO_SPECTATORCONNECT: 50,
	DDEMO_SPECTATORDISCONNECT: 51,
	DDEMO_CHATMESSAGE: 52,
	DDEMO_PLAYERRENAME: 53,
	DDEMO_PLAYERMODELCHANGE: 54,
	DDEMO_GENERICSOUNDDATA: 55,
	DDEMO_GENERICSOUNDSTATDATA: 56,
	DDEMO_TEAMSELECT: 57,
	DDEMO_CTF_EVENT_FLAGTAKEN: 58,
	DDEMO_CTF_EVENT_FLAGCAPTURE: 59,
	DDEMO_CTF_EVENT_FLAGDROP: 60,
	DDEMO_CTF_EVENT_FLAGPICKUP: 61,
	DDEMO_CTF_EVENT_FLAGDROP_APPLY: 62,
	DDEMO_CTF_EVENT_FLAGRETURN: 63,
	DDEMO_CTF_GAMESTATE: 64,
	DDEMO_CTF_EVENT_FLAGDROPGAMESTATE: 65,
	DDEMO_CTF_GAMESTATESCORE: 66,
	DDEMO_CTF_FLAGCARRIER: 67,
	DDEMO_DOM_CAPTURE: 68,
	DDEMO_DOM_SCORECHANGED: 69,
	DDEMO_WPN_EVENT_WEAPONDROP: 70,
	DDEMO_WPN_EVENT_PICKUP: 71,
	DDEMO_WPN_EVENT_WEAPONDROP_APPLY: 72,
	DDEMO_WPN_EVENT_WEAPONDROPGAMESTATE: 73,
	DDEMO_DOM_CAPTUREGAMESTATE: 74,
	DDEMO_NEW_SHAFTBEGIN: 75,
	DDEMO_NEW_SHAFTEND: 76,
	DDEMO_POWERUP_EVENT_POWERUPDROP: 77,
	DDEMO_POWERUP_EVENT_PICKUP: 78,
	DDEMO_POWERUP_EVENT_POWERUPDROPGAMESTATE: 79,

	// conn: additional demo ctf events
	DDEMO_CTF_EVENT_FLAGTAKEN_RED     : 80,
	DDEMO_CTF_EVENT_FLAGCAPTURE_RED   : 81,
	DDEMO_CTF_EVENT_FLAGDROP_RED      : 82,
	
	
	
	
	
	// demo player state
	PUV3_DIR0: 1,
	PUV3_DIR1: 2,
	PUV3_DIR2: 8,
	PUV3_DIR3: 16,
	PUV3_DEAD0: 32,
	PUV3_DEAD1: 64,
	PUV3_DEAD2: 128,
	PUV3_WPN0: 256,
	PUV3_WPN1: 512,
	PUV3_WPN2: 1024,
	PUV3_WPN3: 2048,
	PUV3_WPN4: 4096,
	PUV3_WPN5: 8192,
	PUV3_WPN6: 16384,
	PUV3_WPN7: 32768,
	PUV3B_WPN8: 1,
	PUV3B_CROUCH: 2,
	PUV3B_BALLOON: 8,
	
	
	
	
};

